Лабораторная работа №1
Programming-Classrooms/practicalworks-AlexanderChernyavski pull request #7
Opened 2023-12-24 03:58 UTC by AlexanderChernyavski

## Pull Request лабораторной работы №1

### Условие лабраторной работы
Разработать консольное приложение для вычисления приближённого
значения функции, используя представление ее в виде ряда Тейлора.
Вычисления заканчивать, когда очередное слагаемое окажется по модулю
меньше заданного числа 𝑒𝑝𝑠𝑖𝑙𝑜𝑛, где 0 < 𝑒𝑝𝑠𝑖𝑙𝑜𝑛 <= 10−𝑘
, 𝑘 – натуральное
число, 𝑘 > 1. Сравнить полученный результат со значением, вычисленным с
помощью стандартных функций.Значение 𝑥 и 𝑘 ввести по запросу.

2023-12-27 19:56 UTC, AnnaSatolina requested changes

2023-12-27 19:56 UTC, AnnaSatolina commented on laboratory-task-1/main.cpp
> +	while (fabs(p) >= eps)
немного не поняла почему трай в трае

2024-01-11 16:52 UTC, ShurupJosephson requested changes
По мелочи

2024-01-11 16:52 UTC, ShurupJosephson commented on laboratory-task-1/main.cpp
> +	помощью стандартных функций.Значение 𝑥 и 𝑘 ввести по запросу.*/
Не по стандарту

2024-01-11 16:52 UTC, ShurupJosephson commented on laboratory-task-1/main.cpp
> +			std::cout << "arth=" << 0.5 * logf((1 + x) / (1 - x)) << '\n';
Что за отступ?

2024-01-11 16:52 UTC, ShurupJosephson commented on laboratory-task-1/main.cpp
> +#include<iostream>
Пробел лень было ставить?

2024-01-11 18:21 UTC, AlexandrOsiptsov requested changes
Снова мимо

2024-01-11 18:21 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +помощью стандартных функций.Значение 𝑥 и 𝑘 ввести по запросу.*/
Стандарт

2024-01-11 18:35 UTC, AlexandrOsiptsov approved these changes
+

2024-01-11 18:47 UTC, AnnaSatolina approved these changes
Саша, можно сливать ветки

2024-06-17 16:19 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, merged